[package]
name = "pki-chain"
version = "0.1.0"
edition = "2021"


[dependencies]
libblockchain = { path = "../libblockchain" }
anyhow = "1.0"
secrecy = { version = "0.8", features = ["serde"] }
rpassword = "7.3"
hex = "0.4.3"
openssl = "0.10"
