# PKI Chain Configuration

[blockchains]
certificate_path = "data/certificates"
private_key_path = "data/private_keys"

[key_exports]
key_export_directory_path = "exports/keystore"
app_key_path = "key/app.key"
root_key_name = "0.key.enc"
key_archive_name = "key-archive.tar"
